workflows:
  ios-workflow:
    name: iOS Workflow

    environment:
      flutter: 3.19.1
      xcode: 16.2

    scripts:
      - name: Check Flutter and Dart version
        script: |
          echo "===== FLUTTER ====="
          which flutter
          flutter --version

          echo "===== DART ====="
          dart --version

          echo "===== SDWebImage LOCK ====="
          grep -A3 -B3 "SDWebImage (" ios/Podfile.lock

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build IPA
        script: |
          flutter build ipa \
            --release \
            --export-options-plist /Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - klartdean@gmail.com