name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+51
environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  video_player: 2.10.1
  firebase_auth: 6.5.6
  firebase_storage: 13.4.5
  firebase_remote_config: ^6.5.5
  url_launcher: ^6.3.1
  share_plus: ^10.0.0
  intl: ">=0.18.1 <0.21.0"
  cloud_firestore: 6.7.1
  firebase_messaging: 16.4.3
  firebase_core: 4.12.1
  http: ^1.2.2
  path_provider: ^2.1.4
  gal: ^2.3.2
  dio: ^5.7.0
  local_auth: ^2.3.0
  ai_barcode_scanner: ^7.1.0
  qr_flutter: ^4.1.0
  provider: ^6.1.5+1
  flutter_staggered_grid_view: ^0.7.0
  audio_video_progress_bar: ^2.0.3
  flutter_staggered_animations: ^1.0.0
  photo_view: ^0.15.0
  record: ^6.0.0
  flutter_image_compress: ^2.4.0
  audioplayers: ^6.5.1
  firebase_app_check: ^0.4.1+1
  badges: ^3.1.2
  connectivity_plus: ^6.1.4
  font_awesome_flutter: ^10.8.0
  flutter_rating_bar: ^4.0.1
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  geocoding: ^3.0.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  get: ^4.6.6
  cloud_functions: 6.1.8
  firebase_database: ^12.1.0
  uuid: ^4.5.1
  shimmer: ^3.0.0
  fl_chart: ^0.69.0
  video_compress: ^3.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/phone_icon.png
    - assets/images/google_icon.png
    - assets/images/lock_icon.png
    - assets/images/person_icon.png
    - assets/images/email_icon.png
    - assets/locations.json
    - assets/logo.png
    - assets/aba_qr.png
    - assets/khqr_new.png
    - assets/banner/
    - assets/flags/
    - assets/icons/
    - assets/json/cambodia_locations.json

  fonts:
    - family: Siemreap
      fonts:
        - asset: assets/fonts/Siemreap-Regular.ttf
    - family: KHMEROS
      fonts:
        - asset: assets/fonts/KHMEROS.ttf
