import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:image_picker/image_picker.dart';
import 'package:flutter_image_compress/flutter_image_compress.dart';
import 'package:my_app/location_picker.dart';
import 'package:path_provider/path_provider.dart';
import 'package:intl/intl.dart';
import 'package:get/get.dart' show Trans;
import 'package:shared_preferences/shared_preferences.dart';

class AddPreOrderScreen extends StatefulWidget {
  const AddPreOrderScreen({super.key});
  @override
  State<AddPreOrderScreen> createState() => _AddPreOrderScreenState();
}

class _AddPreOrderScreenState extends State<AddPreOrderScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _priceController = TextEditingController();
  final _phoneController = TextEditingController();
  final _locationController = TextEditingController();
  final _descController = TextEditingController();
  final _dateController = TextEditingController();
  final List<File> _images = [];
  String? _selectedUnit;
  String? currentUid;
  bool _isUploading = false;

  final List<String> _units = ['គីឡូក្រាម (Kg)','តោន (Ton)','ហិកតា (Ha)','គ្រឿង','ផ្លែ','កាន','ធុង','ដើម','បាច់','បាវ','ស្រះ','កញ្ចប់','ឡូ','ដុំ','ម៉ែត្រ','លីត្រ','ផ្សេងៗ'];
  String _unitLabel(String unit) { const keys = {'គីឡូក្រាម (Kg)':'unit_kg','តោន (Ton)':'unit_ton','ហិកតា (Ha)':'unit_hectare','គ្រឿង':'unit_item','ផ្លែ':'unit_fruit','កាន':'unit_can','ធុង':'unit_drum','ដើម':'unit_tree','បាច់':'unit_bunch','បាវ':'unit_sack','ស្រះ':'unit_pond','កញ្ចប់':'unit_package','ឡូ':'unit_lot','ដុំ':'unit_piece','ម៉ែត្រ':'unit_meter','លីត្រ':'unit_liter','ផ្សេងៗ':'unit_other'}; return (keys[unit] ?? unit).tr; }

  @override void initState(){super.initState();_loadCurrentUid();CambodiaLocationService.load();}
  @override void dispose(){_nameController.dispose();_priceController.dispose();_phoneController.dispose();_locationController.dispose();_descController.dispose();_dateController.dispose();super.dispose();}
  Future<void> _loadCurrentUid() async { final prefs=await SharedPreferences.getInstance(); final uid=prefs.getString('user_uid')??''; if(mounted)setState(()=>currentUid=uid.isNotEmpty?uid:null); }
  Future<void> _pickImages() async { final picked=await ImagePicker().pickMultiImage(); if(picked.isEmpty)return; if(_images.length+picked.length>7){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('pre_max_images'.tr)));return;} for(final x in picked){final f=await _compressImage(File(x.path));if(mounted)setState(()=>_images.add(f));}}
  Future<File> _compressImage(File file) async {final dir=await getTemporaryDirectory();final path='${dir.path}/img_${DateTime.now().millisecondsSinceEpoch}.jpg';final result=await FlutterImageCompress.compressAndGetFile(file.absolute.path,path,quality:60);return File(result!.path);}
  Future<void> _selectDate(BuildContext context) async {final picked=await showDatePicker(context:context,initialDate:DateTime.now().add(const Duration(days:1)),firstDate:DateTime.now(),lastDate:DateTime(2101));if(picked!=null)setState(()=>_dateController.text=DateFormat('dd-MM-yyyy').format(picked));}

  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text('pre_add_title'.tr,style:const TextStyle(fontFamily:'Siemreap',fontSize:18)),backgroundColor:Colors.orange[800],foregroundColor:Colors.white,elevation:0),body:GestureDetector(onTap:()=>FocusScope.of(context).unfocus(),behavior:HitTestBehavior.translucent,child:SingleChildScrollView(padding:const EdgeInsets.all(16),child:Form(key:_formKey,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[_title('pre_images_title'.tr),const SizedBox(height:10),_imageArea(),const SizedBox(height:20),_title('pre_details'.tr),const SizedBox(height:10),_field(_nameController,'pre_product_name'.tr,'pre_product_hint'.tr,Icons.inventory_2_outlined,maxLength:60),Row(children:[Expanded(flex:2,child:_field(_priceController,'pre_price_khr'.tr,'0.00',Icons.sell_outlined,isNumber:true,isPrice:true)),const SizedBox(width:10),Expanded(child:_unitDropdown())]),GestureDetector(onTap:()=>_selectDate(context),child:AbsorbPointer(child:_field(_dateController,'pre_harvest_date'.tr,'pre_select_date'.tr,Icons.calendar_today_outlined))),Row(children:[Expanded(flex:3,child:InkWell(onTap:()=>showLocationPicker(context,onSelected:(location)=>setState(()=>_locationController.text=location.toString())),borderRadius:BorderRadius.circular(12),child:Container(padding:const EdgeInsets.symmetric(horizontal:12,vertical:15),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(12),border:Border.all(color:Colors.grey.shade300)),child:Row(children:[Icon(Icons.location_on_outlined,color:Colors.orange.shade800,size:22),const SizedBox(width:10),Expanded(child:Text(_locationController.text.isEmpty?'pre_select_location'.tr:_locationController.text,overflow:TextOverflow.ellipsis,maxLines:1,style:TextStyle(fontSize:14,fontFamily:'Siemreap',color:_locationController.text.isEmpty?Colors.grey.shade600:Colors.black87)))])))),const SizedBox(width:10),Expanded(child:Container(padding:const EdgeInsets.symmetric(vertical:10),decoration:BoxDecoration(color:Colors.grey.shade100,borderRadius:BorderRadius.circular(12),border:Border.all(color:Colors.grey.shade300)),child:Column(children:[Icon(Icons.map_outlined,color:Colors.grey.shade400,size:20),const Text('Map',style:TextStyle(fontSize:10,color:Colors.grey))])))]),const SizedBox(height:16),_field(_phoneController,'pre_phone'.tr,'012 345 xxx',Icons.phone_android_outlined,isNumber:true),_field(_descController,'pre_description'.tr,'pre_description_hint'.tr,Icons.notes,maxLines:4),const SizedBox(height:30),_submit(),const SizedBox(height:20)])))));

  Widget _title(String t)=>Text(t,style:const TextStyle(fontWeight:FontWeight.bold,fontSize:15,fontFamily:'Siemreap'));
  Widget _imageArea()=>SizedBox(height:110,child:ListView.builder(scrollDirection:Axis.horizontal,itemCount:_images.length+1,itemBuilder:(c,i){if(i==_images.length)return GestureDetector(onTap:_pickImages,child:Container(width:100,margin:const EdgeInsets.only(right:10),decoration:BoxDecoration(color:Colors.grey[100],borderRadius:BorderRadius.circular(12),border:Border.all(color:Colors.orange.withOpacity(.5))),child:const Icon(Icons.add_a_photo_outlined,color:Colors.orange,size:30)));return Stack(children:[Container(width:100,margin:const EdgeInsets.only(right:10),decoration:BoxDecoration(borderRadius:BorderRadius.circular(12),image:DecorationImage(image:FileImage(_images[i]),fit:BoxFit.cover))),Positioned(top:5,right:15,child:GestureDetector(onTap:()=>setState(()=>_images.removeAt(i)),child:const CircleAvatar(radius:10,backgroundColor:Colors.red,child:Icon(Icons.close,color:Colors.white,size:14))))]);}));
  Widget _field(TextEditingController c,String label,String hint,IconData icon,{bool isNumber=false,bool isPrice=false,int maxLines=1,int? maxLength})=>Padding(padding:const EdgeInsets.only(bottom:16),child:TextFormField(controller:c,keyboardType:isNumber?TextInputType.number:(maxLines>1?TextInputType.multiline:TextInputType.text),textInputAction:maxLines>1?TextInputAction.newline:TextInputAction.next,maxLines:maxLines,maxLength:maxLength,inputFormatters:[if(isPrice)ThousandsSeparatorInputFormatter(),if(maxLength!=null)LengthLimitingTextInputFormatter(maxLength)],decoration:InputDecoration(labelText:label,hintText:hint,prefixIcon:Icon(icon,size:20),filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(12))),validator:(v)=>(v??'').isEmpty?'pre_required'.tr:null));
  Widget _unitDropdown()=>Container(margin:const EdgeInsets.only(bottom:16),padding:const EdgeInsets.symmetric(horizontal:12),height:58,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(12),border:Border.all(color:Colors.grey.shade300)),child:DropdownButtonFormField<String>(value:_selectedUnit,isExpanded:true,decoration:const InputDecoration(border:InputBorder.none),hint:Text('pre_select_unit'.tr),items:_units.map((e)=>DropdownMenuItem(value:e,child:Text(_unitLabel(e)))).toList(),onChanged:(v)=>setState(()=>_selectedUnit=v),validator:(v)=>v==null?'pre_unit_required'.tr:null));
  Widget _submit()=>SizedBox(width:double.infinity,height:55,child:ElevatedButton(onPressed:(_isUploading||_images.isEmpty)?null:_submitData,style:ElevatedButton.styleFrom(backgroundColor:Colors.orange[800]),child:_isUploading?const CircularProgressIndicator(color:Colors.white):Text('pre_submit'.tr,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.bold,fontFamily:'Siemreap'))));
  Future<void> _submitData() async {if(!_formKey.currentState!.validate()||_images.isEmpty)return;if(currentUid==null||currentUid!.isEmpty){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('pre_login_required'.tr),backgroundColor:Colors.red));return;}if(_locationController.text.isEmpty){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('pre_location_required'.tr),backgroundColor:Colors.red));return;}setState(()=>_isUploading=true);try{final urls=<String>[];for(var i=0;i<_images.length;i++){final ref=FirebaseStorage.instance.ref().child('pre_orders/$currentUid/${DateTime.now().millisecondsSinceEpoch}_$i.jpg');await ref.putFile(_images[i]);urls.add(await ref.getDownloadURL());}final harvest=DateFormat('dd-MM-yyyy').parse(_dateController.text);await FirebaseFirestore.instance.collection('pre_orders').add({'owner_id':currentUid,'product_name':_nameController.text.trim(),'price':double.tryParse(_priceController.text.replaceAll(',',''))??0.0,'unit':_selectedUnit??'មិនបានជ្រើសរើស','harvest_date':Timestamp.fromDate(harvest),'location':_locationController.text.trim(),'phone':_phoneController.text.trim(),'description':_descController.text.trim(),'images':urls,'created_at':FieldValue.serverTimestamp(),'status':'active'});if(mounted){setState(()=>_isUploading=false);Navigator.pop(context);ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('pre_submit_success'.tr),backgroundColor:Colors.green));}}catch(e){if(mounted){setState(()=>_isUploading=false);ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('pre_submit_error'.trParams({'error':'$e'})),backgroundColor:Colors.red));}}}
}

class ThousandsSeparatorInputFormatter extends TextInputFormatter {static final NumberFormat _formatter=NumberFormat('#,###');@override TextEditingValue formatEditUpdate(TextEditingValue oldValue,TextEditingValue newValue){if(newValue.text.isEmpty)return newValue;final value=int.tryParse(newValue.text.replaceAll(',',''));if(value==null)return oldValue;final text=_formatter.format(value);return newValue.copyWith(text:text,selection:TextSelection.collapsed(offset:text.length));}}
