import 'dart:async';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/services.dart';
import 'package:my_app/order_history_screen.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'receipt_screen.dart';
import 'package:intl/intl.dart';
import 'order_tracking_screen.dart';
import 'marketplace_analytics_service.dart';

class CartScreen extends StatefulWidget { const CartScreen({super.key}); @override State<CartScreen> createState()=>_CartScreenState(); }
class _CartScreenState extends State<CartScreen> with AutomaticKeepAliveClientMixin,WidgetsBindingObserver {
 @override bool get wantKeepAlive=>true; bool _isProcessingCheckout=false,_isAnyFieldFocused=false,_isLoadingUserId=true; final currencyFormat=NumberFormat('#,###','en_US'); String? _currentUserId; final Map<String,TextEditingController> _qtyControllers={}; final Map<String,FocusNode> _qtyFocusNodes={}; final Map<String,int> _localQuantities={}; final Map<String,Timer> _debounceTimers={}; static const _debounceMs=500; List<QueryDocumentSnapshot>? _cachedDocs; double _cachedTotal=0;
 @override void initState(){super.initState();WidgetsBinding.instance.addObserver(this);_loadUserId();}
 @override void dispose(){WidgetsBinding.instance.removeObserver(this);for(final c in _qtyControllers.values)c.dispose();for(final n in _qtyFocusNodes.values)n.dispose();for(final t in _debounceTimers.values)t.cancel();super.dispose();}
 @override void didChangeAppLifecycleState(AppLifecycleState state){}
 Future<void> _loadUserId() async{final p=await SharedPreferences.getInstance();if(mounted)setState((){_currentUserId=p.getString('user_uid');_isLoadingUserId=false;});}
 void _updateQuantity(String id,int q,{int maxQty=999}){q=q.clamp(1,maxQty.clamp(1,999));setState(()=>_localQuantities[id]=q);_debounceTimers[id]?.cancel();_debounceTimers[id]=Timer(const Duration(milliseconds:_debounceMs),()=>FirebaseFirestore.instance.collection('carts').doc(id).update({'quantity':q}).catchError((e)=>debugPrint('Firestore update failed: $e')));}
 Future<void> _flushPendingUpdates() async{final fs=<Future>[];for(final e in _debounceTimers.entries){e.value.cancel();final q=_localQuantities[e.key];if(q!=null)fs.add(FirebaseFirestore.instance.collection('carts').doc(e.key).update({'quantity':q}));}_debounceTimers.clear();if(fs.isNotEmpty)await Future.wait(fs);}
 int _getQuantity(QueryDocumentSnapshot d)=>_localQuantities[d.id]??int.tryParse(d['quantity']?.toString()??'1')??1;
 double _calculateTotal(List<QueryDocumentSnapshot> ds)=>ds.fold(0,(s,d)=>s+(double.tryParse(d['price'].toString().replaceAll(',',''))??0)*_getQuantity(d));
 void _dismissKeyboard()=>FocusScope.of(context).unfocus();
 @override Widget build(BuildContext context){super.build(context);return GestureDetector(onTap:_dismissKeyboard,behavior:HitTestBehavior.translucent,child:Scaffold(backgroundColor:const Color(0xFFF5F5F7),appBar:AppBar(title:Text('កន្ត្រករបស់ខ្ញុំ'.tr,style:const TextStyle(fontWeight:FontWeight.bold,color:Colors.white)),backgroundColor:Colors.green,actions:[IconButton(icon:const Icon(Icons.history_rounded,color:Colors.white),onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const OrderHistoryScreen()))),IconButton(icon:const Icon(Icons.local_shipping_rounded,color:Colors.white),onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const OrderTrackingScreen())))]),body:Column(children:[_buildOrderTracking(),Expanded(child:_isLoadingUserId?const Center(child:CircularProgressIndicator()):_currentUserId==null?Center(child:Text('មិនអាចទាញព័ត៌មានអ្នកប្រើបាន'.tr)):StreamBuilder<QuerySnapshot>(stream:FirebaseFirestore.instance.collection('carts').where('customer_id',isEqualTo:_currentUserId).orderBy('created_at',descending:true).snapshots(),builder:(context,s){if(s.connectionState==ConnectionState.waiting&&_cachedDocs!=null)return _buildCartContent(_cachedDocs!,_cachedTotal);if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(!s.hasData||s.data!.docs.isEmpty){_cachedDocs=null;_cachedTotal=0;_localQuantities.clear();return _buildEmptyCart();}final docs=s.data!.docs;for(final d in docs){_localQuantities.putIfAbsent(d.id,()=>int.tryParse(d['quantity']?.toString()??'1')??1);}_localQuantities.removeWhere((id,_)=>!docs.any((d)=>d.id==id));final total=_calculateTotal(docs);_cachedDocs=docs;_cachedTotal=total;return _buildCartContent(docs,total);} ))])));}
 Widget _buildCartContent(List<QueryDocumentSnapshot> docs,double total)=>Column(children:[Expanded(child:ListView.builder(padding:const EdgeInsets.all(10),itemCount:docs.length,itemBuilder:(_,i)=>_buildModernCartItem(docs[i]))),if(!_isAnyFieldFocused)_buildCheckoutButton(total,docs)]);
 Widget _buildModernCartItem(QueryDocumentSnapshot item){final data=item.data() as Map<String,dynamic>;final tracks=data['track_stock']==true;final stock=data['stock_quantity'] is num?(data['stock_quantity'] as num).toInt():int.tryParse(data['stock_quantity']?.toString()??'')??0;final raw=data['stock_unit']?.toString().trim()??'';final unit=['item','items','item(s)'].contains(raw.toLowerCase())?'':raw;final maxQty=tracks?stock.clamp(1,999):999;var qty=_getQuantity(item).clamp(1,maxQty);final price=double.tryParse(item['price'].toString().replaceAll(',',''))??0;final c=_qtyControllers.putIfAbsent(item.id,()=>TextEditingController(text:'$qty'));final f=_qtyFocusNodes.putIfAbsent(item.id,()=>FocusNode());if(!f.hasListeners)f.addListener(()=>mounted?setState(()=>_isAnyFieldFocused=_qtyFocusNodes.values.any((n)=>n.hasFocus)):null);if(!f.hasFocus&&c.text!='$qty')c.text='$qty';return Container(margin:const EdgeInsets.only(bottom:12),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20)),child:Row(children:[ClipRRect(borderRadius:BorderRadius.circular(8),child:(item['image_url']??'').toString().isNotEmpty?Image.network(item['image_url'],width:55,height:55,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const SizedBox(width:55,height:55,child:Icon(Icons.image_not_supported))):const SizedBox(width:55,height:55,child:Icon(Icons.image))),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(item['product_name']??'គ្មានឈ្មោះ',style:const TextStyle(fontWeight:FontWeight.bold)),Text('${currencyFormat.format(price)} ៛',style:const TextStyle(color:Colors.red,fontWeight:FontWeight.bold)),if(tracks)Text(stock<=0?'អស់ពីស្តុក'.tr:'${'នៅសល់'.tr}: $stock${unit.isEmpty?'':' $unit'}',style:TextStyle(fontSize:11,color:stock<=0?Colors.red:Colors.green)),Row(children:[_qtyBtn(Icons.remove,()=>_updateQuantity(item.id,qty-1,maxQty:maxQty)),SizedBox(width:60,height:35,child:TextField(controller:c,focusNode:f,keyboardType:TextInputType.number,textAlign:TextAlign.center,inputFormatters:[LengthLimitingTextInputFormatter(3),FilteringTextInputFormatter.digitsOnly],onSubmitted:(v){_validateAndUpdateQty(item.id,v,c,maxQty:maxQty);_dismissKeyboard();},onEditingComplete:()=>_validateAndUpdateQty(item.id,c.text,c,maxQty:maxQty))),_qtyBtn(Icons.add,()=>_updateQuantity(item.id,qty+1,maxQty:maxQty))])])),Column(children:[Text('${currencyFormat.format(price*qty)} ៛',style:const TextStyle(fontWeight:FontWeight.bold,color:Colors.blue)),IconButton(icon:const Icon(Icons.delete_outline),onPressed:()=>item.reference.delete())]) ]));}
 void _validateAndUpdateQty(String id,String value,TextEditingController c,{int maxQty=999}){var q=int.tryParse(value)??1;q=q.clamp(1,maxQty);c.text='$q';_updateQuantity(id,q,maxQty:maxQty);}
 Widget _qtyBtn(IconData icon,VoidCallback onTap)=>InkWell(onTap:(){_dismissKeyboard();onTap();},child:Container(padding:const EdgeInsets.all(2),decoration:BoxDecoration(border:Border.all(color:Colors.grey.shade300),borderRadius:BorderRadius.circular(5)),child:Icon(icon,size:16)));
 Widget _buildCheckoutButton(double total,List<QueryDocumentSnapshot> docs)=>Container(padding:const EdgeInsets.all(20),color:Colors.white,child:SafeArea(child:ElevatedButton(style:ElevatedButton.styleFrom(backgroundColor:_isProcessingCheckout?Colors.grey:Colors.green,minimumSize:const Size(double.infinity,55)),onPressed:_isProcessingCheckout?null:()async{setState(()=>_isProcessingCheckout=true);final sellerIds=docs.map((d)=>((d.data() as Map<String,dynamic>)['seller_id']??'').toString()).where((e)=>e.isNotEmpty).toSet().toList();final productIds=docs.map((d)=>((d.data() as Map<String,dynamic>)['product_id']??'').toString()).where((e)=>e.isNotEmpty).toList();await MarketplaceAnalyticsService.logEvent(type:'checkout_started',buyerId:_currentUserId??FirebaseAuth.instance.currentUser?.uid??'',sellerId:sellerIds.length==1?sellerIds.first:(sellerIds.isEmpty?'':'multiple'),productId:productIds.isEmpty?'':productIds.first,sellerIds:sellerIds,productIds:productIds,source:'cart',totalAmount:total);await _flushPendingUpdates();if(mounted){setState(()=>_isProcessingCheckout=false);Navigator.push(context,MaterialPageRoute(builder:(_)=>ReceiptScreen(cartDocs:docs)));}},child:_isProcessingCheckout?const CircularProgressIndicator(color:Colors.white):FittedBox(child:Text('${'បន្តទៅការទូទាត់'.tr} (${currencyFormat.format(total)} ៛)',style:const TextStyle(fontSize:14,fontWeight:FontWeight.bold,color:Colors.white))))));
 Widget _buildEmptyCart()=>Center(child:Text('មិនទាន់មានទំនិញក្នុងកន្ត្រកទេ'.tr)); Widget _buildOrderTracking()=>const SizedBox();
}
