import 'package:flutter/widgets.dart';

/// Returns a translated label without changing the Khmer value stored in
/// Firestore. Filters and queries must continue using the original value.
String localizedCategoryLabel(BuildContext context, String value) {
  if (Localizations.localeOf(context).languageCode != 'en') return value;

  const labels = <String, String>{
    'ទាំងអស់': 'All',
    'ទំនិញរបស់ខ្ញុំ': 'My products',
    'គ្រឿងចក្រ': 'Machinery',
    'សម្ភារៈកសិកម្ម': 'Farm supplies',
    'ពូជដំណាំ': 'Crop seeds & plants',
    'ពូជសត្វចិញ្ចឹម': 'Livestock breeds',
    'ជីនិងថ្នាំ': 'Fertilizers & chemicals',
    'បន្លែផ្លែឈើ': 'Fruits & vegetables',
    'ត្រីសាច់': 'Fish & meat',
    'សេវាកម្ម': 'Services',
    'ផ្សេងៗ': 'Other',
    'ថ្មី': 'New',
    'មួយទឹក': 'Used',
    'កាប់សាច់': 'For parts',
    'គ្រឿងបន្លាស់': 'Spare parts',
    'ម៉ាស៊ីន': 'Machines',
    'ឧបករណ៍': 'Equipment',
    'ឈើហូបផ្លែ': 'Fruit trees',
    'បន្លែ': 'Vegetables',
    'ផ្ការ': 'Flowers',
    'ឈើព្រៃ': 'Forest trees',
    'គោ': 'Cattle',
    'ក្របី': 'Buffalo',
    'ជ្រូក': 'Pigs',
    'ចៀម': 'Sheep',
    'ពពែ': 'Goats',
    'មាន់': 'Chickens',
    'ទា': 'Ducks',
    'ក្ងាន': 'Geese',
    'ក្រួច': 'Quail',
    'អណ្ដើក/កន្ឋាយ': 'Turtles & tortoises',
    'អណ្ដើក/កន្ធាយ': 'Turtles & tortoises',
    'ត្រី': 'Fish',
    'កង្កែប': 'Frogs',
    'ពស់': 'Snakes',
    'ជន្លេន': 'Earthworms',
    'ជី': 'Fertilizer',
    'ថ្នាំ': 'Agricultural chemicals',
    'វីតាមីន': 'Vitamins',
    'ចំណីសត្វ': 'Animal feed',
    'ផ្លែឈើ': 'Fruit',
    'គ្រឿងទេស': 'Spices',
    'អាហារផ្អាប់': 'Preserved food',
    'ស៊ុត': 'Eggs',
    'សាច់': 'Meat',
    'អណ្ដើក': 'Turtles',
    'ក្ដាម': 'Crabs',
    'សេវាកម្មសត្វ': 'Animal services',
    'ដំណាំ': 'Crop services',
    'ទឹក/ភ្លើង': 'Water & electricity',
    'ហិរញ្ញវត្ថុ': 'Finance',
    'ច្បាប់': 'Legal services',
    'ដីកសិកម្ម': 'Agricultural land',
    'កសិដ្ឋាន': 'Farms',
    'តំណាងចែកចាយ/ហ្វ្រែនឆាយ': 'Distributorship / franchise',
    'ផលិតផលឌីជីថល': 'Digital products',
    'សៀវភៅកសិកម្ម': 'Agriculture books',
  };

  return labels[value] ?? value;
}
