import 'dart:io';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:image_picker/image_picker.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter_image_compress/flutter_image_compress.dart';
import 'package:path_provider/path_provider.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:geocoding/geocoding.dart';
import 'localized_text.dart';
import 'location_picker.dart';
import 'map_picker_screen.dart';

class EditShopScreen extends StatefulWidget {
  const EditShopScreen({super.key});
  @override State<EditShopScreen> createState() => _EditShopScreenState();
}

class _EditShopScreenState extends State<EditShopScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _bioController = TextEditingController();
  final _phoneController = TextEditingController();
  final _addressController = TextEditingController();
  String _userId = '';
  bool _isLoading = false;
  bool _isDataLoading = true;
  String? _shopTier;
  double? _shopLatitude, _shopLongitude;
  String? _shopProvince, _shopDistrict, _shopCommune;
  bool _removeShopPin = false;
  File? _profileImage, _coverImage;
  String? _profileImageUrl, _coverImageUrl;
  final ImagePicker _picker = ImagePicker();
  bool get _canUseShopMap => _shopTier == 'basic' || _shopTier == 'premium';
  bool get _hasShopPin => _shopLatitude != null && _shopLongitude != null && !_removeShopPin;

  @override void initState(){super.initState();_loadUserId();}
  Future<void> _loadUserId() async {try{final prefs=await SharedPreferences.getInstance();final uid=prefs.getString('user_uid');if(!mounted)return;if(uid!=null&&uid.isNotEmpty){setState(()=>_userId=uid);await _loadCurrentData();}else{final user=FirebaseAuth.instance.currentUser;if(user!=null){setState(()=>_userId=user.uid);await prefs.setString('user_uid',user.uid);await _loadCurrentData();}else{setState(()=>_isDataLoading=false);_showError(appText(context,km:'រកមិនឃើញអ្នកប្រើ សូមចូលគណនីម្តងទៀត',en:'User not found. Please log in again.'));}}}catch(e){if(mounted){setState(()=>_isDataLoading=false);_showError('Error: $e');}}}
  Future<void> _loadCurrentData() async {try{final doc=await FirebaseFirestore.instance.collection('users').doc(_userId).get();if(doc.exists&&mounted){final data=doc.data()!;setState((){_nameController.text=data['name']??'';_bioController.text=data['bio']??'';_phoneController.text=data['phone']??'';_addressController.text=data['address']??'';_shopTier=data['shop_tier']?.toString();_shopLatitude=(data['shop_latitude'] as num?)?.toDouble();_shopLongitude=(data['shop_longitude'] as num?)?.toDouble();_shopProvince=data['shop_province']?.toString();_shopDistrict=data['shop_district']?.toString();_shopCommune=data['shop_commune']?.toString();_profileImageUrl=data['photoUrl'];_coverImageUrl=data['coverUrl'];_removeShopPin=false;_isDataLoading=false;});}else if(mounted){setState(()=>_isDataLoading=false);}}catch(e){if(mounted){setState(()=>_isDataLoading=false);_showError(appText(context,km:'មិនអាចផ្ទុកទិន្នន័យបាន',en:'Unable to load data.'));}}}
  Future<void> _pickImage(bool profile) async {final x=await _picker.pickImage(source:ImageSource.gallery,maxWidth:profile?400:800,maxHeight:400,imageQuality:80);if(x!=null&&mounted)setState((){if(profile){_profileImage=File(x.path);}else{_coverImage=File(x.path);}});}
  Future<File?> _compressImage(File file,bool profile) async {try{final d=await getTemporaryDirectory();final r=await FlutterImageCompress.compressAndGetFile(file.path,'${d.path}/${profile?'profile':'cover'}_${DateTime.now().millisecondsSinceEpoch}.jpg',quality:70,minWidth:profile?300:800,minHeight:profile?300:400);return r==null?null:File(r.path);}catch(_){return file;}}
  Future<String?> _uploadImage(File file,bool profile) async {final f=await _compressImage(file,profile);if(f==null)return null;final ref=FirebaseStorage.instance.ref().child('shop_images/${profile?'profile':'cover'}_${_userId}_${DateTime.now().millisecondsSinceEpoch}.jpg');await ref.putFile(f);return ref.getDownloadURL();}
  Future<void> _chooseShopAdministrativeLocation() async {if(!_canUseShopMap)return;await showLocationPicker(context,onSelected:(l){if(mounted)setState((){_shopProvince=l.province;_shopDistrict=l.district;_shopCommune=l.commune;_addressController.text=l.toString();});});}
  Future<void> _pickShopMapLocation() async {if(!_canUseShopMap)return;final selected=await Navigator.push<LatLng>(context,MaterialPageRoute(builder:(_)=>MapPickerScreen(initialLat:_hasShopPin?_shopLatitude:null,initialLng:_hasShopPin?_shopLongitude:null,isShopLocation:true)));if(selected==null||!mounted)return;setState((){_shopLatitude=selected.latitude;_shopLongitude=selected.longitude;_removeShopPin=false;});try{final p=await placemarkFromCoordinates(selected.latitude,selected.longitude);if(p.isNotEmpty&&mounted&&_addressController.text.trim().isEmpty){final x=p.first;final parts=<String?>[x.street,x.subLocality,x.locality,x.subAdministrativeArea,x.administrativeArea].whereType<String>().where((e)=>e.trim().isNotEmpty).toSet();if(parts.isNotEmpty)setState(()=>_addressController.text=parts.join(', '));}}catch(_){}}
  void _removeShopLocationPin(){if(_canUseShopMap)setState((){_shopLatitude=null;_shopLongitude=null;_removeShopPin=true;});}
  Widget _buildShopLocationSection(){if(!_canUseShopMap)return Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.grey.shade100,borderRadius:BorderRadius.circular(12),border:Border.all(color:Colors.grey.shade300)),child:Row(children:[const Icon(Icons.lock_outline,color:Colors.grey),const SizedBox(width:10),Expanded(child:Text(appText(context,km:'Upgrade ទៅ Blue ឬ Gold ដើម្បីបន្ថែមទីតាំងហាងលើផែនទី',en:'Upgrade to Blue or Gold to add your shop location on the map.'),style:const TextStyle(fontFamily:'Siemreap',fontSize:12)))]));return Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(12),border:Border.all(color:Colors.green.shade200)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Icon(Icons.store_mall_directory_outlined,color:Colors.green.shade700),const SizedBox(width:8),Expanded(child:Text(appText(context,km:'ទីតាំងហាង',en:'Shop location'),style:const TextStyle(fontFamily:'Siemreap',fontWeight:FontWeight.bold))),if(_hasShopPin)IconButton(onPressed:_removeShopLocationPin,icon:const Icon(Icons.close,color:Colors.red))]),Text(_hasShopPin?'${_shopLatitude!.toStringAsFixed(6)}, ${_shopLongitude!.toStringAsFixed(6)}':appText(context,km:'មិនទាន់បានដៅ Pin',en:'No pin selected yet'),style:TextStyle(fontSize:11,color:_hasShopPin?Colors.green.shade700:Colors.grey.shade600)),const SizedBox(height:10),Row(children:[Expanded(child:OutlinedButton.icon(onPressed:_chooseShopAdministrativeLocation,icon:const Icon(Icons.location_city,size:18),label:Text(appText(context,km:'ខេត្ត/ស្រុក/ឃុំ',en:'Address area'),maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontFamily:'Siemreap',fontSize:11)))),const SizedBox(width:8),Expanded(child:ElevatedButton.icon(onPressed:_pickShopMapLocation,icon:const Icon(Icons.map_outlined,size:18),label:Text(_hasShopPin?appText(context,km:'កែ Pin',en:'Edit pin'):appText(context,km:'ដៅ Pin',en:'Drop pin'),style:const TextStyle(fontFamily:'Siemreap',fontSize:11)),style:ElevatedButton.styleFrom(backgroundColor:Colors.green.shade700,foregroundColor:Colors.white)))]) ]));}
  Future<void> _saveChanges() async {if(!_formKey.currentState!.validate()||_userId.isEmpty)return;setState(()=>_isLoading=true);try{final newProfile=_profileImage==null?null:await _uploadImage(_profileImage!,true);final newCover=_coverImage==null?null:await _uploadImage(_coverImage!,false);final data=<String,dynamic>{'name':_nameController.text.trim(),'bio':_bioController.text.trim(),'phone':_phoneController.text.trim(),'address':_addressController.text.trim(),'updated_at':FieldValue.serverTimestamp()};if(_canUseShopMap)data.addAll({'shop_latitude':_hasShopPin?_shopLatitude:FieldValue.delete(),'shop_longitude':_hasShopPin?_shopLongitude:FieldValue.delete(),'shop_province':_shopProvince?.trim().isNotEmpty==true?_shopProvince:FieldValue.delete(),'shop_district':_shopDistrict?.trim().isNotEmpty==true?_shopDistrict:FieldValue.delete(),'shop_commune':_shopCommune?.trim().isNotEmpty==true?_shopCommune:FieldValue.delete()});if(newProfile!=null)data['photoUrl']=newProfile;if(newCover!=null)data['coverUrl']=newCover;await FirebaseFirestore.instance.collection('users').doc(_userId).set(data,SetOptions(merge:true));if(mounted){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(appText(context,km:'បានរក្សាទុកការផ្លាស់ប្តូរ',en:'Changes saved')),backgroundColor:Colors.green));Navigator.pop(context,true);}}catch(e){if(mounted)_showError('${appText(context,km:'មិនអាចរក្សាទុកបាន',en:'Unable to save')}: $e');}finally{if(mounted)setState(()=>_isLoading=false);}}
  void _showError(String m){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(m),backgroundColor:Colors.red));}
  @override void dispose(){_nameController.dispose();_bioController.dispose();_phoneController.dispose();_addressController.dispose();super.dispose();}
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFFF5F7FA),appBar:AppBar(title:Text(appText(context,km:'កែសម្រួលហាង',en:'Edit shop')),actions:[IconButton(onPressed:_isLoading?null:_saveChanges,icon:const Icon(Icons.check,color:Colors.green))]),body:_isDataLoading?const Center(child:CircularProgressIndicator()):Form(key:_formKey,child:ListView(padding:const EdgeInsets.all(16),children:[_imageBox(false),const SizedBox(height:16),_imageBox(true),const SizedBox(height:20),_field(_nameController,appText(context,km:'ឈ្មោះហាង *',en:'Shop name *'),Icons.store,required:true),_field(_phoneController,appText(context,km:'លេខទូរស័ព្ទ *',en:'Phone number *'),Icons.phone,required:true),_field(_addressController,appText(context,km:'អាសយដ្ឋាន',en:'Address'),Icons.location_on,maxLines:2),_buildShopLocationSection(),const SizedBox(height:16),_field(_bioController,appText(context,km:'ជីវប្រវត្តិហាង (Bio)',en:'Shop bio'),Icons.description,maxLines:4),const SizedBox(height:24),ElevatedButton.icon(onPressed:_isLoading?null:_saveChanges,icon:const Icon(Icons.save),label:Text(appText(context,km:'រក្សាទុកការផ្លាស់ប្តូរ',en:'Save changes')),style:ElevatedButton.styleFrom(backgroundColor:Colors.green.shade700,foregroundColor:Colors.white,minimumSize:const Size.fromHeight(50)))])));
  Widget _imageBox(bool profile)=>InkWell(onTap:()=>_pickImage(profile),child:Container(height:profile?110:150,decoration:BoxDecoration(color:Colors.grey.shade200,borderRadius:BorderRadius.circular(12),image:(profile?_profileImage:_coverImage)!=null?DecorationImage(image:FileImage((profile?_profileImage:_coverImage)!),fit:BoxFit.cover):(profile?_profileImageUrl:_coverImageUrl)?.isNotEmpty==true?DecorationImage(image:NetworkImage((profile?_profileImageUrl:_coverImageUrl)!),fit:BoxFit.cover):null),child:const Center(child:Icon(Icons.add_a_photo,size:32))));
  Widget _field(TextEditingController c,String label,IconData icon,{bool required=false,int maxLines=1})=>Padding(padding:const EdgeInsets.only(bottom:16),child:TextFormField(controller:c,maxLines:maxLines,validator:required?(v)=>(v??'').trim().isEmpty?label:null:null,decoration:InputDecoration(labelText:label,prefixIcon:Icon(icon),border:OutlineInputBorder(borderRadius:BorderRadius.circular(12)))));
}
