import 'dart:io';
import 'dart:async';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'category_localization.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/services.dart';
import 'package:get/get_core/src/get_main.dart';
import 'package:get/get_navigation/src/extension_navigation.dart';
import 'package:intl/intl.dart';
import 'package:my_app/edit_shopscreen.dart';
import 'package:my_app/share_service.dart';
import 'package:my_app/shop_upgrade_screen.dart';
import 'package:path_provider/path_provider.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:screenshot/screenshot.dart';
import 'package:share_plus/share_plus.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:shimmer/shimmer.dart';
import 'product_detail.dart';
import 'chat_screen.dart';
import 'package:fl_chart/fl_chart.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:url_launcher/url_launcher.dart';
import 'localized_text.dart';

class SellerProfileScreen extends StatefulWidget { final String sellerId,sellerName; const SellerProfileScreen({super.key,required this.sellerId,required this.sellerName}); @override State<SellerProfileScreen> createState()=>_SellerProfileScreenState(); }
class _SellerProfileScreenState extends State<SellerProfileScreen>{
 String? _currentUserId,_cachedCurrentUid,_filterMainCategory,_filterSubCategory,_filterSubSubCategory; bool _isCheckingFollow=false; final ValueNotifier<bool> _showSellerPhoneNotifier=ValueNotifier(false); Timer? _phoneHideTimer; late final Future<String> _sellerPhoneFuture; StreamSubscription<QuerySnapshot>? _cartSubscription; final Set<String> _cartProductIds={},_cartBusyIds={}; final ValueNotifier<int> _cartRevision=ValueNotifier(0); final ScreenshotController _screenshotController=ScreenshotController();
 final Map<String,dynamic> _subCategories={'គ្រឿងចក្រ':['ទាំងអស់','ថ្មី','មួយទឹក','កាប់សាច់','គ្រឿងបន្លាស់'],'សម្ភារៈកសិកម្ម':{'ទាំងអស់':[],'ម៉ាស៊ីន':['ទាំងអស់','ថ្មី','មួយទឹក','កាប់សាច់'],'ឧបករណ៍':['ទាំងអស់','ថ្មី','មួយទឹក','កាប់សាច់'],'គ្រឿងបន្លាស់':['ទាំងអស់','ថ្មី','មួយទឹក','កាប់សាច់']},'ពូជដំណាំ':['ទាំងអស់','ឈើហូបផ្លែ','បន្លែ','ផ្ការ','ឈើព្រៃ','ផ្សេងៗ'],'ពូជសត្វចិញ្ចឹម':['ទាំងអស់','គោ','ក្របី','ជ្រូក','ចៀម','ពពែ','មាន់','ទា','ក្ងាន','ក្រួច','អណ្ដើក/កន្ឋាយ','ត្រី','កង្កែប','ពស់','ជន្លេន','ផ្សេងៗ'],'ជីនិងថ្នាំ':['ទាំងអស់','ជី','ថ្នាំ','វីតាមីន','ចំណីសត្វ','ផ្សេងៗ'],'បន្លែផ្លែឈើ':['ទាំងអស់','បន្លែ','ផ្លែឈើ','គ្រឿងទេស','អាហារផ្អាប់','ស៊ុត','ផ្សេងៗ'],'ត្រីសាច់':['ទាំងអស់','ត្រី','សាច់','កង្កែប','អណ្ដើក','ពស់','ក្ដាម','ផ្សេងៗ'],'សេវាកម្ម':['ទាំងអស់','សេវាកម្មសត្វ','ដំណាំ','ម៉ាស៊ីន','គ្រឿងចក្រ','ទឹក/ភ្លើង','ហិរញ្ញវត្ថុ','ច្បាប់','ផ្សេងៗ'],'ផ្សេងៗ':['ទាំងអស់','ដីកសិកម្ម','កសិដ្ឋាន','តំណាងចែកចាយ/ហ្វ្រែនឆាយ','ផលិតផលឌីជីថល','សៀវភៅកសិកម្ម','ផ្សេងៗ']};
 @override void initState(){super.initState();_sellerPhoneFuture=_getSellerPhoneFromProducts(widget.sellerId);_loadUserId();}
 @override void dispose(){_phoneHideTimer?.cancel();_cartSubscription?.cancel();_cartRevision.dispose();_showSellerPhoneNotifier.dispose();super.dispose();}
 void _notifyCartChanged()=>_cartRevision.value++;
 String _maskSellerPhone(String p){final v=p.trim().replaceAll(RegExp(r'\s+'),'');if(v.isEmpty)return'';if(v.length<=3)return'XXX';return '${v.substring(0,v.length-3)}XXX';}
 Future<void> _recordMarketplaceEvent(String type)async{try{await FirebaseFirestore.instance.collection('marketplace_events').add({'type':type,'buyerId':_currentUserId??FirebaseAuth.instance.currentUser?.uid??'','sellerId':widget.sellerId,'productId':'','source':'seller_shop','createdAt':FieldValue.serverTimestamp()});}catch(e){debugPrint('Marketplace analytics error: $e');}}
 void _revealSellerPhoneTemporarily(){_phoneHideTimer?.cancel();_showSellerPhoneNotifier.value=true;_recordMarketplaceEvent('phone_reveal');_phoneHideTimer=Timer(const Duration(seconds:5),(){if(mounted)_showSellerPhoneNotifier.value=false;});}
 Future<void> _loadUserId()async{final prefs=await SharedPreferences.getInstance();String? uid=prefs.getString('user_uid');uid??=FirebaseAuth.instance.currentUser?.uid;if(uid!=null)await prefs.setString('user_uid',uid);if(!mounted)return;setState((){_currentUserId=uid;_cachedCurrentUid=uid;});if(uid!=null&&uid.isNotEmpty){_checkIfFollowing();_listenToCart();}_recordProfileView();}
 Future<void> _checkIfFollowing()async{if(_currentUserId==null||_isCheckingFollow)return;_isCheckingFollow=true;try{await FirebaseFirestore.instance.collection('users').doc(widget.sellerId).collection('followers').doc(_currentUserId).get();}finally{_isCheckingFollow=false;}}
 Future<void> _recordProfileView()async{if(_currentUserId==null||_currentUserId==widget.sellerId)return;try{await FirebaseFirestore.instance.collection('users').doc(widget.sellerId).collection('profile_visitors').doc(_currentUserId).set({'visited_at':FieldValue.serverTimestamp()},SetOptions(merge:true));}catch(e){debugPrint('$e');}}
 Future<String> _getSellerPhoneFromProducts(String id)async{try{final q=await FirebaseFirestore.instance.collection('products').where('seller_id',isEqualTo:id).orderBy('created_at',descending:true).limit(1).get();if(q.docs.isNotEmpty){final d=q.docs.first.data();return (d['phone1']??d['seller_phone']??'').toString();}}catch(e){debugPrint('$e');}return'';}
 void _listenToCart(){_cartSubscription?.cancel();final uid=_currentUserId;if(uid==null||uid.isEmpty)return;_cartSubscription=FirebaseFirestore.instance.collection('carts').where('customer_id',isEqualTo:uid).snapshots().listen((s){final ids=s.docs.map((d)=>(d.data()['product_id']??'').toString()).where((e)=>e.isNotEmpty).toSet();if(!mounted)return;_cartProductIds..clear()..addAll(ids);_cartBusyIds.removeWhere((id)=>!ids.contains(id));_notifyCartChanged();});}
 Future<void> _removeSellerProductFromCart(String id)async{final uid=_currentUserId;if(uid==null||id.isEmpty||_cartBusyIds.contains(id))return;_cartBusyIds.add(id);_notifyCartChanged();try{final s=await FirebaseFirestore.instance.collection('carts').where('customer_id',isEqualTo:uid).get();final b=FirebaseFirestore.instance.batch();bool found=false;for(final d in s.docs){if((d.data()['product_id']??'').toString()==id){b.delete(d.reference);found=true;}}if(found)await b.commit();_cartProductIds.remove(id);}finally{_cartBusyIds.remove(id);_notifyCartChanged();}}
 Future<void> _fastAddToCart(Map<String,dynamic> p)async{final uid=_currentUserId,id=(p['id']??'').toString();if(uid==null||id.isEmpty||_cartProductIds.contains(id)||_cartBusyIds.contains(id))return;_cartBusyIds.add(id);_notifyCartChanged();try{final existing=await FirebaseFirestore.instance.collection('carts').where('customer_id',isEqualTo:uid).get();if(existing.docs.any((d)=>(d.data()['product_id']??'').toString()==id)){_cartProductIds.add(id);return;}final seller=await FirebaseFirestore.instance.collection('users').doc(widget.sellerId).get(),sd=seller.data();final imgs=p['image_urls'];await FirebaseFirestore.instance.collection('carts').add({'product_id':id,'product_name':p['product_name']??'គ្មានឈ្មោះ','price':p['price']??0,'currency':p['currency']??'៛','image_url':p['image_url']??(imgs is List&&imgs.isNotEmpty?imgs.first:''),'quantity':1,'customer_id':uid,'created_at':FieldValue.serverTimestamp(),'seller_id':widget.sellerId,'seller_name':sd?['name']??widget.sellerName,'seller_phone':sd?['phone']??'','seller_photo':sd?['photoUrl']??''});_cartProductIds.add(id);if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(appText(context,km:'✅ បន្ថែមទៅកន្ត្រករួចរាល់!',en:'✅ Added to cart.')),backgroundColor:Colors.green));}catch(e){debugPrint('$e');}finally{_cartBusyIds.remove(id);_notifyCartChanged();}}
 Future<void> _addToChat(Map<String,dynamic> p)async{if(_currentUserId==null)return;final imgs=p['image_urls'];final room=_currentUserId!.compareTo(widget.sellerId)<=0?'${_currentUserId}_${widget.sellerId}':'${widget.sellerId}_$_currentUserId';await FirebaseFirestore.instance.collection('chat_items').add({'product_id':p['id']??'','product_name':p['product_name']??'','price':p['price']??0,'currency':p['currency']??'៛','image_url':p['image_url']??(imgs is List&&imgs.isNotEmpty?imgs.first:''),'customer_id':_currentUserId,'seller_id':widget.sellerId,'chat_room_id':room,'created_at':FieldValue.serverTimestamp()});}
 Stream<QuerySnapshot> _getFilteredStream(){Query q=FirebaseFirestore.instance.collection('products').where('seller_id',isEqualTo:widget.sellerId);if(_filterMainCategory!=null)q=q.where('category',isEqualTo:_filterMainCategory);if(_filterSubCategory!=null&&_filterSubCategory!='ទាំងអស់')q=q.where('sub_category',isEqualTo:_filterSubCategory);if(_filterSubSubCategory!=null&&_filterSubSubCategory!='ទាំងអស់')q=q.where('sub_sub_category',isEqualTo:_filterSubSubCategory);return q.orderBy('created_at',descending:true).snapshots();}
 @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFFF8F9FA),body:CustomScrollView(slivers:[_buildSliverAppBar(context),SliverToBoxAdapter(child:_buildSellerInfoCard(context)),SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.fromLTRB(16,20,16,8),child:Row(children:[Container(width:4,height:24,color:Colors.green[700]),const SizedBox(width:8),Expanded(child:Text(appText(context,km:'ទំនិញដាក់លក់',en:'Products for sale'),style:const TextStyle(fontSize:14,fontWeight:FontWeight.bold))),IconButton(icon:const Icon(Icons.filter_list_rounded),onPressed:_showFilterSheet)]))),_buildProductsGrid(context)]));
 Widget _buildSliverAppBar(BuildContext c)=>SliverAppBar(expandedHeight:175,pinned:true,backgroundColor:Colors.green[700],title:Text(widget.sellerName,style:const TextStyle(color:Colors.white,fontSize:16,fontWeight:FontWeight.bold)),actions:[if(_cachedCurrentUid==widget.sellerId)IconButton(icon:const Icon(Icons.edit,color:Colors.white),onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const EditShopScreen()))),IconButton(icon:const Icon(Icons.share,color:Colors.white),onPressed:_shareShopWithWatermark)],flexibleSpace:FlexibleSpaceBar(background:StreamBuilder<DocumentSnapshot>(stream:FirebaseFirestore.instance.collection('users').doc(widget.sellerId).snapshots(),builder:(c,s){final d=s.data?.data()as Map<String,dynamic>?;final cover=d?['coverUrl']??'',photo=d?['photoUrl']??'';return Stack(fit:StackFit.expand,children:[cover.isNotEmpty?CachedNetworkImage(imageUrl:cover,fit:BoxFit.cover):Container(color:Colors.green[700]),Container(color:Colors.black.withOpacity(.25)),Positioned(bottom:10,left:0,right:0,child:Center(child:CircleAvatar(radius:34,backgroundImage:photo.isNotEmpty?CachedNetworkImageProvider(photo):null,child:photo.isEmpty?const Icon(Icons.person):null))) ]);}))); 
 Future<void> _openShopDirections(double lat,double lng)async{await launchUrl(Uri.parse('https://www.google.com/maps/dir/?api=1&destination=$lat,$lng'),mode:LaunchMode.externalApplication);}
 Widget _buildShopMapPreview(double lat,double lng){final loc=LatLng(lat,lng);return Padding(padding:const EdgeInsets.only(top:4,bottom:10),child:GestureDetector(onTap:()=>_openShopDirections(lat,lng),child:AspectRatio(aspectRatio:4,child:ClipRRect(borderRadius:BorderRadius.circular(12),child:AbsorbPointer(child:GoogleMap(initialCameraPosition:CameraPosition(target:loc,zoom:15.5),markers:{Marker(markerId:const MarkerId('shop_location'),position:loc)},zoomControlsEnabled:false,myLocationButtonEnabled:false,mapToolbarEnabled:false,scrollGesturesEnabled:false,zoomGesturesEnabled:false))))));}
 Widget _buildSellerInfoCard(BuildContext c)=>StreamBuilder<DocumentSnapshot>(stream:FirebaseFirestore.instance.collection('users').doc(widget.sellerId).snapshots(),builder:(c,s){if(!s.hasData||!s.data!.exists)return const SizedBox.shrink();final d=s.data!.data()as Map<String,dynamic>,tier=d['shop_tier']as String?,followers=(d['followers_count']??0).toString(),address=(d['address']??appText(c,km:'មិនទាន់មានទីតាំង',en:'Location not provided')).toString(),lat=(d['shop_latitude']as num?)?.toDouble(),lng=(d['shop_longitude']as num?)?.toDouble();return Container(margin:const EdgeInsets.fromLTRB(12,10,12,0),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(14)),child:Column(children:[Row(mainAxisAlignment:MainAxisAlignment.spaceEvenly,children:[_buildStatItem(Icons.people,followers,appText(c,km:'អ្នកតាមដាន',en:'Followers')),if(_currentUserId!=widget.sellerId)_FollowButton(sellerId:widget.sellerId,currentUserId:_currentUserId,compact:true)]),const SizedBox(height:8),FutureBuilder<String>(future:_sellerPhoneFuture,builder:(c,p){final phone=p.data??'';return Row(children:[Expanded(flex:4,child:ElevatedButton.icon(onPressed:()async{await _recordMarketplaceEvent('chat_seller');if(c.mounted)Navigator.push(c,MaterialPageRoute(builder:(_)=>ChatScreen(seller_id:widget.sellerId,receiver_id:widget.sellerId,productName:widget.sellerName,productId:'general')));},icon:const Icon(Icons.chat_bubble_outline,size:15),label:Text(appText(c,km:'ឆាត',en:'Chat')))),if(phone.isNotEmpty)...[const SizedBox(width:6),Expanded(flex:6,child:ValueListenableBuilder<bool>(valueListenable:_showSellerPhoneNotifier,builder:(c,show,_)=>(Row(children:[const Icon(Icons.phone,size:14),Expanded(child:Text(show?phone:_maskSellerPhone(phone))),IconButton(onPressed:show?(){_phoneHideTimer?.cancel();_showSellerPhoneNotifier.value=false;}:_revealSellerPhoneTemporarily,icon:Icon(show?Icons.visibility_off:Icons.visibility,size:15))]))))]]);}),Padding(padding:const EdgeInsets.symmetric(vertical:8),child:Row(mainAxisAlignment:MainAxisAlignment.center,children:[const Icon(Icons.location_on,color:Colors.redAccent,size:16),Flexible(child:Text(address,maxLines:2,overflow:TextOverflow.ellipsis))])),if((tier=='basic'||tier=='premium')&&lat!=null&&lng!=null)_buildShopMapPreview(lat,lng),if(_cachedCurrentUid==widget.sellerId)SizedBox(width:double.infinity,child:ElevatedButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const ShopUpgradeScreen())),icon:const Icon(Icons.verified_user),label:Text(appText(c,km:'ដំឡើងឋានៈហាង',en:'Upgrade shop'))))]));});
 Widget _buildProductsGrid(BuildContext c)=>StreamBuilder<QuerySnapshot>(stream:_getFilteredStream(),builder:(c,s){if(s.connectionState==ConnectionState.waiting)return SliverToBoxAdapter(child:_buildShimmerGrid());if(!s.hasData||s.data!.docs.isEmpty)return SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.all(32),child:Center(child:Text(appText(c,km:'មិនទាន់មានទំនិញលក់នៅឡើយ',en:'No products for sale yet.')))));final docs=s.data!.docs;return SliverPadding(padding:const EdgeInsets.all(12),sliver:SliverGrid(gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:MediaQuery.of(c).size.width>700?4:2,childAspectRatio:MediaQuery.of(c).size.width>700?.8:.65,crossAxisSpacing:12,mainAxisSpacing:12),delegate:SliverChildBuilderDelegate((c,i){final p=docs[i].data()as Map<String,dynamic>;p['id']=docs[i].id;final id=docs[i].id,imgs=p['image_urls'],img=p['image_url']??(imgs is List&&imgs.isNotEmpty?imgs.first:''),disabled=p['is_locked']==true||p['shop_closed']==true||p['shipping_included']==false;return GestureDetector(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ProductDetailScreen(product:p))),child:Container(decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(16)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(flex:3,child:ClipRRect(borderRadius:const BorderRadius.vertical(top:Radius.circular(16)),child:img.toString().isNotEmpty?CachedNetworkImage(imageUrl:img.toString(),fit:BoxFit.cover,width:double.infinity):Container(color:Colors.grey[100]))),Expanded(flex:2,child:Padding(padding:const EdgeInsets.all(8),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text((p['product_name']??appText(c,km:'គ្មានឈ្មោះ',en:'Unnamed product')).toString(),maxLines:1,overflow:TextOverflow.ellipsis),Text('${NumberFormat('#,###').format(double.tryParse((p['price']??0).toString())??0)} ${p['currency']??'៛'}',style:TextStyle(color:Colors.red[700],fontWeight:FontWeight.bold)),Row(mainAxisAlignment:MainAxisAlignment.end,children:[GestureDetector(onTap:()=>_addToChat(p),child:const Icon(Icons.chat_bubble_outline,color:Colors.orange,size:16)),const SizedBox(width:10),ValueListenableBuilder<int>(valueListenable:_cartRevision,builder:(c,_,__) {final inCart=_cartProductIds.contains(id),busy=_cartBusyIds.contains(id);return GestureDetector(onTap:busy?null:inCart?()=>_removeSellerProductFromCart(id):disabled?null:()=>_fastAddToCart(p),child:busy?const SizedBox(width:16,height:16,child:CircularProgressIndicator(strokeWidth:2)):Icon(inCart?Icons.check_circle:Icons.add_shopping_cart,color:inCart?Colors.green:disabled?Colors.grey:Colors.green,size:16));})])])))])));},childCount:docs.length)));});
 void _showFilterSheet(){showModalBottomSheet(context:context,builder:(ctx)=>ListView(padding:const EdgeInsets.all(16),children:[Text(appText(context,km:'តម្រៀបទំនិញ',en:'Filter products'),style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:12),Wrap(spacing:8,children:_subCategories.keys.map((cat)=>ChoiceChip(label:Text(localizedCategoryLabel(context,cat)),selected:_filterMainCategory==cat,onSelected:(v){setState((){_filterMainCategory=v?cat:null;_filterSubCategory=null;_filterSubSubCategory=null;});Navigator.pop(ctx);})).toList())]));}
 Future<void> _shareShopWithWatermark()async{final msg='${widget.sellerName}\nhttps://sesanshop.com/shop/${widget.sellerId}';try{await Share.share(msg);}catch(e){debugPrint('$e');}}
 Widget _buildStatItem(IconData i,String v,String l)=>Column(children:[Icon(i,color:Colors.green[700],size:20),Text(v,style:const TextStyle(fontWeight:FontWeight.bold)),Text(l,style:const TextStyle(fontSize:10))]);
 Widget _buildShimmerGrid()=>Padding(padding:const EdgeInsets.all(12),child:GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:MediaQuery.of(context).size.width>700?4:2,childAspectRatio:MediaQuery.of(context).size.width>700?.8:.65),itemCount:4,itemBuilder:(_,__)=>Shimmer.fromColors(baseColor:Colors.grey[300]!,highlightColor:Colors.grey[100]!,child:Container(color:Colors.white))));
}
class _FollowButton extends StatefulWidget{final String sellerId;final String? currentUserId;final bool compact;const _FollowButton({required this.sellerId,required this.currentUserId,this.compact=false});@override State<_FollowButton> createState()=>_FollowButtonState();}
class _FollowButtonState extends State<_FollowButton>{bool _following=false,_loading=false;@override void initState(){super.initState();_check();}Future<void> _check()async{if(widget.currentUserId==null)return;final d=await FirebaseFirestore.instance.collection('users').doc(widget.sellerId).collection('followers').doc(widget.currentUserId).get();if(mounted)setState(()=>_following=d.exists);}Future<void> _toggle()async{if(widget.currentUserId==null||_loading||widget.currentUserId==widget.sellerId)return;setState(()=>_loading=true);final f=FirebaseFirestore.instance.collection('users').doc(widget.sellerId).collection('followers').doc(widget.currentUserId),g=FirebaseFirestore.instance.collection('users').doc(widget.currentUserId).collection('following').doc(widget.sellerId),b=FirebaseFirestore.instance.batch();if(_following){b.delete(f);b.delete(g);}else{b.set(f,{'user_id':widget.currentUserId,'followed_at':FieldValue.serverTimestamp()});b.set(g,{'seller_id':widget.sellerId,'followed_at':FieldValue.serverTimestamp()});}await b.commit();if(mounted)setState((){_following=!_following;_loading=false;});}@override Widget build(BuildContext c)=>IconButton(onPressed:_loading?null:_toggle,icon:_loading?const SizedBox(width:16,height:16,child:CircularProgressIndicator(strokeWidth:2)):Icon(_following?Icons.check:Icons.person_add,color:Colors.green[700]),iconSize:widget.compact?16:24);}
