import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'localized_text.dart';

class SellerDigitalAgreementScreen extends StatefulWidget { const SellerDigitalAgreementScreen({super.key}); @override State<SellerDigitalAgreementScreen> createState()=>_SellerDigitalAgreementScreenState(); }
class _SellerDigitalAgreementScreenState extends State<SellerDigitalAgreementScreen> {
 static const String agreementVersion='1.0'; final ScrollController _scrollController=ScrollController(); String? _userId; bool _loading=true,_saving=false,_reachedEnd=false,_confirmed=false,_alreadyAccepted=false; DateTime? _acceptedAt; bool get _isEnglish=>Localizations.localeOf(context).languageCode=='en';
 @override void initState(){super.initState();_scrollController.addListener(_checkScrollPosition);_loadAgreementStatus();}
 void _checkScrollPosition(){if(!_scrollController.hasClients||_reachedEnd)return;if(_scrollController.position.extentAfter<80)setState(()=>_reachedEnd=true);}
 Future<void> _loadAgreementStatus() async {final prefs=await SharedPreferences.getInstance();final uid=FirebaseAuth.instance.currentUser?.uid??prefs.getString('user_uid');if(uid==null||uid.isEmpty){if(mounted)setState(()=>_loading=false);return;}try{final doc=await FirebaseFirestore.instance.collection('users').doc(uid).get();final data=doc.data();final accepted=data?['seller_agreement_accepted']==true&&data?['seller_agreement_version']==agreementVersion;final timestamp=data?['seller_agreement_accepted_at'];if(!mounted)return;setState((){_userId=uid;_alreadyAccepted=accepted;_confirmed=accepted;_reachedEnd=accepted;_acceptedAt=timestamp is Timestamp?timestamp.toDate():null;_loading=false;});}catch(_){if(mounted)setState(()=>_loading=false);}}
 Future<void> _acceptAgreement() async {final uid=_userId;if(uid==null||!_confirmed||!_reachedEnd||_saving)return;setState(()=>_saving=true);try{await FirebaseFirestore.instance.collection('users').doc(uid).set({'seller_agreement_accepted':true,'seller_agreement_version':agreementVersion,'seller_agreement_accepted_at':FieldValue.serverTimestamp(),'seller_agreement_language':_isEnglish?'en':'km','seller_agreement_title':'Sesan App Seller Digital Agreement'},SetOptions(merge:true));if(!mounted)return;setState((){_alreadyAccepted=true;_acceptedAt=DateTime.now();});ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(appText(context,km:'បានយល់ព្រមលើកិច្ចព្រមព្រៀងរួចរាល់',en:'Agreement accepted successfully.')),backgroundColor:Colors.green));}catch(_){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(appText(context,km:'មិនអាចរក្សាទុកការយល់ព្រមបានទេ',en:'Could not save your acceptance.')),backgroundColor:Colors.red));}finally{if(mounted)setState(()=>_saving=false);}}
 @override void dispose(){_scrollController..removeListener(_checkScrollPosition)..dispose();super.dispose();}
 @override Widget build(BuildContext context){final sections=_isEnglish?_englishSections:_khmerSections;return Scaffold(backgroundColor:const Color(0xFFF5F7F5),appBar:AppBar(title:Text(appText(context,km:'កិច្ចព្រមព្រៀងឌីជីថលអ្នកលក់',en:'Seller digital agreement'),style:const TextStyle(fontFamily:'Siemreap',fontSize:16,fontWeight:FontWeight.bold)),backgroundColor:Colors.green.shade700,foregroundColor:Colors.white,centerTitle:true),body:_loading?const Center(child:CircularProgressIndicator(color:Colors.green)):Column(children:[Expanded(child:ListView(controller:_scrollController,padding:const EdgeInsets.fromLTRB(14,14,14,20),children:[_header(),if(_alreadyAccepted)...[const SizedBox(height:10),_accepted()],const SizedBox(height:12),...sections.asMap().entries.map((e)=>_section(e.key+1,e.value.title,e.value.body)),const SizedBox(height:8),Text(appText(context,km:'ដោយចុច «យល់ព្រម» អ្នកបញ្ជាក់ថាបានអាន យល់ និងព្រមគោរពកិច្ចព្រមព្រៀងនេះ។',en:'By tapping Accept, you confirm that you have read, understood, and agreed to this agreement.'),style:const TextStyle(fontFamily:'Siemreap',fontSize:12,height:1.55,fontWeight:FontWeight.w600))])),_acceptArea()]));}
 Widget _header()=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(gradient:LinearGradient(colors:[Colors.green.shade800,Colors.green.shade600]),borderRadius:BorderRadius.circular(16)),child:Column(children:[const Icon(Icons.draw_outlined,color:Colors.white,size:38),const SizedBox(height:8),Text(appText(context,km:'រវាង Sesan App និងអ្នកលក់',en:'Between Sesan App and the Seller'),style:const TextStyle(color:Colors.white,fontFamily:'Siemreap',fontSize:17,fontWeight:FontWeight.bold)),const SizedBox(height:5),Text('${appText(context,km:'កំណែ',en:'Version')} $agreementVersion • 14/09/2026',style:const TextStyle(color:Colors.white70,fontSize:11))]));
 Widget _accepted(){String d='';if(_acceptedAt!=null){final x=_acceptedAt!;d=' • ${x.day.toString().padLeft(2,'0')}/${x.month.toString().padLeft(2,'0')}/${x.year}';}return Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.green.shade50,borderRadius:BorderRadius.circular(12),border:Border.all(color:Colors.green.shade200)),child:Row(children:[Icon(Icons.verified_rounded,color:Colors.green.shade700),const SizedBox(width:9),Expanded(child:Text('${appText(context,km:'បានយល់ព្រមរួច',en:'Accepted')}$d',style:TextStyle(color:Colors.green.shade800,fontFamily:'Siemreap',fontWeight:FontWeight.bold,fontSize:12)))]));}
 Widget _section(int n,String title,String body)=>Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(14),border:Border.all(color:Colors.grey.shade200)),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(width:28,height:28,alignment:Alignment.center,decoration:BoxDecoration(color:Colors.green.shade50,shape:BoxShape.circle),child:Text('$n',style:TextStyle(color:Colors.green.shade800,fontWeight:FontWeight.bold,fontSize:11))),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontFamily:'Siemreap',fontWeight:FontWeight.bold,fontSize:13)),const SizedBox(height:5),Text(body,style:const TextStyle(fontFamily:'Siemreap',fontSize:11.5,height:1.6,color:Colors.black87))]))]));
 Widget _acceptArea(){if(_alreadyAccepted)return SafeArea(top:false,child:Container(width:double.infinity,padding:const EdgeInsets.fromLTRB(16,11,16,12),color:Colors.white,child:Row(mainAxisAlignment:MainAxisAlignment.center,children:[const Icon(Icons.check_circle,color:Colors.green),const SizedBox(width:7),Text(appText(context,km:'កិច្ចព្រមព្រៀងមានសុពលភាព',en:'Agreement is active'),style:const TextStyle(fontFamily:'Siemreap',fontWeight:FontWeight.bold))])));return SafeArea(top:false,child:Container(padding:const EdgeInsets.fromLTRB(12,8,12,12),decoration:const BoxDecoration(color:Colors.white,boxShadow:[BoxShadow(color:Colors.black12,blurRadius:8)]),child:Column(mainAxisSize:MainAxisSize.min,children:[if(!_reachedEnd)Text(appText(context,km:'សូមអូសអានដល់ខាងក្រោម',en:'Please scroll to the bottom first'),style:const TextStyle(color:Colors.orange,fontFamily:'Siemreap',fontSize:11)),CheckboxListTile(dense:true,contentPadding:EdgeInsets.zero,value:_confirmed,onChanged:_reachedEnd?(v)=>setState(()=>_confirmed=v==true):null,title:Text(appText(context,km:'ខ្ញុំបានអាន និងយល់ព្រម',en:'I have read and agree'),style:const TextStyle(fontFamily:'Siemreap',fontSize:12)),controlAffinity:ListTileControlAffinity.leading),SizedBox(width:double.infinity,height:46,child:ElevatedButton.icon(onPressed:_confirmed&&_reachedEnd&&!_saving?_acceptAgreement:null,icon:_saving?const SizedBox(width:17,height:17,child:CircularProgressIndicator(color:Colors.white,strokeWidth:2)):const Icon(Icons.draw_outlined),label:Text(appText(context,km:'យល់ព្រម',en:'Accept agreement'),style:const TextStyle(fontFamily:'Siemreap',fontWeight:FontWeight.bold)),style:ElevatedButton.styleFrom(backgroundColor:Colors.green.shade700,foregroundColor:Colors.white)))])));}
 static const _khmerSections=[_AgreementSection('គោលបំណង','កិច្ចព្រមព្រៀងនេះកំណត់លក្ខខណ្ឌសម្រាប់ការប្រើ Sesan App ដើម្បីបើកហាង បង្ហោះទំនិញ ទទួលការបញ្ជាទិញ និងទំនាក់ទំនងជាមួយអ្នកទិញ។'),_AgreementSection('ព័ត៌មានអ្នកលក់','អ្នកលក់ត្រូវផ្ដល់ឈ្មោះ លេខទូរស័ព្ទ ទីតាំង និងព័ត៌មានទទួលប្រាក់ឱ្យបានត្រឹមត្រូវ។ អ្នកលក់ទទួលខុសត្រូវចំពោះគណនី និងសកម្មភាពដែលកើតឡើងក្រោមគណនីរបស់ខ្លួន។'),_AgreementSection('ទំនិញ និងខ្លឹមសារ','អ្នកលក់ត្រូវបង្ហោះតែទំនិញពិត ស្របច្បាប់ និងមានការពិពណ៌នា រូបភាព តម្លៃ ទីតាំង និងចំនួនស្តុកត្រឹមត្រូវ។ ហាមបង្ហោះទំនិញក្លែងក្លាយ ខុសច្បាប់ ឬបង្កគ្រោះថ្នាក់។'),_AgreementSection('ការបញ្ជាទិញ និងការដឹកជញ្ជូន','អ្នកលក់ត្រូវពិនិត្យ និងឆ្លើយតប Order ទាន់ពេល រៀបចំទំនិញត្រឹមត្រូវ និងផ្ដល់ព័ត៌មានដឹកជញ្ជូនពិត។ បើមិនអាចបំពេញ Order បាន ត្រូវជូនដំណឹងអ្នកទិញឱ្យបានឆាប់។'),_AgreementSection('កម្រៃសេវា និងប្រាក់ចំណូល','ការបើកហាងមិនគិតថ្លៃ។ ការលក់ដែលបញ្ចប់តាមមុខងារកន្ត្រកមានកម្រៃសេវា 7% លើតម្លៃលក់។ ប្រាក់ចំណូល និងការដកប្រាក់អនុវត្តតាមសមតុល្យ និងនីតិវិធីក្នុង App។'),_AgreementSection('ការបង្វិលប្រាក់ និងវិវាទ','អ្នកលក់ត្រូវសហការផ្ដល់ភស្តុតាង និងដោះស្រាយបញ្ហាទំនិញខុស ខូច បាត់ ឬមិនដូចការពិពណ៌នា។ Sesan App អាចពិនិត្យទិន្នន័យពាក់ព័ន្ធដើម្បីជួយសម្របសម្រួលវិវាទ។'),_AgreementSection('ការផ្អាក ឬបិទហាង','Sesan App អាចផ្អាកទំនិញ មុខងារ Cart ឬគណនីអ្នកលក់ នៅពេលមានការបំពាន ការក្លែងបន្លំ ហានិភ័យសុវត្ថិភាព ឬតម្រូវការតាមច្បាប់។'),_AgreementSection('ការកែប្រែកិច្ចព្រមព្រៀង','Sesan App អាចធ្វើបច្ចុប្បន្នភាពលក្ខខណ្ឌនេះ។ បើមានការផ្លាស់ប្ដូរសំខាន់ អ្នកលក់នឹងត្រូវបានស្នើឱ្យអាន និងយល់ព្រមលើកំណែថ្មីមុនបន្តប្រើមុខងារដែលពាក់ព័ន្ធ។')];
 static const _englishSections=[_AgreementSection('Purpose','This agreement sets the conditions for using Sesan App to operate a shop, list products, receive orders, and communicate with buyers.'),_AgreementSection('Seller information','The seller must provide accurate identity, phone, location, and payout information and is responsible for activity under their account.'),_AgreementSection('Products and content','The seller must list genuine and lawful products with accurate descriptions, photos, prices, locations, and stock. Illegal, counterfeit, or dangerous items are prohibited.'),_AgreementSection('Orders and delivery','The seller must review orders promptly, prepare the correct goods, and provide truthful delivery information. Buyers must be informed promptly when an order cannot be fulfilled.'),_AgreementSection('Service fee and earnings','Opening a shop is free. A completed sale through the cart carries a 7% service fee on the sale price. Earnings and withdrawals follow the balance and procedures shown in the app.'),_AgreementSection('Refunds and disputes','The seller must cooperate and provide evidence when goods are incorrect, damaged, missing, or not as described. Sesan App may review relevant records to help mediate disputes.'),_AgreementSection('Suspension or closure','Sesan App may suspend a listing, cart access, or seller account for violations, fraud, safety risks, or legal requirements.'),_AgreementSection('Agreement updates','Sesan App may update these terms. Sellers will be asked to review and accept a new version before continuing relevant features when changes are material.')];
}
class _AgreementSection{final String title,body;const _AgreementSection(this.title,this.body);}
