import 'package:flutter/material.dart';
import 'localized_text.dart';

class SellerGuideScreen extends StatelessWidget {
  const SellerGuideScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final lessons = <_SellerLesson>[
      _SellerLesson(icon: Icons.storefront_outlined, color: Colors.green, titleKm: '១. ចាប់ផ្ដើមលក់', titleEn: '1. Start selling', stepsKm: const ['ចូល Profile ហើយប្ដូរទៅ Seller Mode។','កែព័ត៌មានហាង៖ ឈ្មោះ រូបភាព លេខទូរស័ព្ទ និងអាសយដ្ឋាន។','ចុចប៊ូតុង + ដើម្បីបង្ហោះទំនិញថ្មី។','បំពេញរូបភាព ឈ្មោះ តម្លៃ ប្រភេទ ស្តុក និងទីតាំង។'], stepsEn: const ['Open Profile and switch to Seller Mode.','Complete your shop name, photos, phone number, and address.','Tap the + button to post a new product.','Add photos, name, price, category, stock, and location.']),
      _SellerLesson(icon: Icons.shopping_cart_checkout, color: Colors.teal, titleKm: '២. លក់តាមកន្ត្រក', titleEn: '2. Sell through the cart', stepsKm: const ['Switch ពណ៌បៃតងមានន័យថាទំនិញអាចទិញតាមកន្ត្រកបាន។','Switch ពណ៌ប្រផេះមានន័យថាបិទការលក់តាមកន្ត្រក។','ការលក់តាមកន្ត្រកមានកម្រៃសេវា 7% លើតម្លៃលក់។','បើហាងបិទបណ្ដោះអាសន្ន Cart ទាំងអស់ត្រូវផ្អាក ប៉ុន្តែ Chat នៅប្រើបាន។'], stepsEn: const ['A green switch means the product can be bought through the cart.','A grey switch means cart sales are disabled.','Cart sales have a 7% service fee on the sale price.','Closing the shop pauses cart sales while chat remains available.']),
      _SellerLesson(icon: Icons.inventory_2_outlined, color: Colors.blue, titleKm: '៣. គ្រប់គ្រងស្តុក', titleEn: '3. Manage stock', stepsKm: const ['ចូល គ្រប់គ្រងការបង្ហោះ ហើយជ្រើស Tab ទំនិញលក់។','ចុច − ឬ + ដើម្បីកែស្តុកម្ដងមួយ។','ចុចលើលេខស្តុក ដើម្បីកាត់ បន្ថែម ឬកំណត់ចំនួនសល់តែម្ដង។','ពេលស្តុកស្មើ 0 ទំនិញនឹងមិនអាចបញ្ជាទិញបាន។'], stepsEn: const ['Open Manage posts and select the For sale tab.','Tap − or + to change stock one at a time.','Tap the stock number to deduct, add, or set the remaining amount.','A product cannot be ordered when its stock reaches zero.']),
      _SellerLesson(icon: Icons.receipt_long_outlined, color: Colors.orange, titleKm: '៤. ទទួល និងគ្រប់គ្រង Order', titleEn: '4. Receive and manage orders', stepsKm: const ['ពិនិត្យ Order ថ្មីក្នុង Seller Mode។','ផ្ទៀងផ្ទាត់ទំនិញ ចំនួន អាសយដ្ឋាន និងលេខទូរស័ព្ទ។','Confirm Order មុនរៀបចំ និងដឹកជញ្ជូនទំនិញ។','ធ្វើបច្ចុប្បន្នភាពស្ថានភាពឱ្យអ្នកទិញអាចតាមដានបាន។'], stepsEn: const ['Check new orders in Seller Mode.','Verify the product, quantity, address, and phone number.','Confirm the order before preparing and shipping it.','Update the status so the buyer can track the order.']),
      _SellerLesson(icon: Icons.account_balance_wallet_outlined, color: Colors.indigo, titleKm: '៥. ប្រាក់ចំណូល និងដកប្រាក់', titleEn: '5. Earnings and withdrawals', stepsKm: const ['ប្រាក់ពី Order ដែលបានបញ្ចប់បង្ហាញក្នុង Wallet អ្នកលក់។','ពិនិត្យសមតុល្យ និងប្រវត្តិប្រតិបត្តិការមុនដកប្រាក់។','បញ្ចូលចំនួន និងព័ត៌មានទទួលប្រាក់ឱ្យបានត្រឹមត្រូវ។','តាមដានស្ថានភាព Pending, Success ឬ Rejected។'], stepsEn: const ['Completed-order earnings appear in the seller wallet.','Check the balance and transaction history before withdrawing.','Enter the amount and payment details carefully.','Track Pending, Success, or Rejected status.']),
      _SellerLesson(icon: Icons.store_mall_directory_outlined, color: Colors.purple, titleKm: '៦. បិទ ឬបើកហាង', titleEn: '6. Close or open your shop', stepsKm: const ['ប្រើ Switch ស្ថានភាពហាងនៅក្នុងហាងរបស់អ្នក។','បិទហាងពេលសម្រាក ឈប់ទទួល Order ឬអស់ទំនិញច្រើន។','ការបិទហាងមិនលុបទំនិញ និងមិនបាត់ការកំណត់ Cart ចាស់ទេ។','បើកហាងវិញពេលត្រៀមទទួលការបញ្ជាទិញ។'], stepsEn: const ['Use the shop-status switch inside your shop.','Close the shop during a break or when you cannot accept orders.','Closing does not delete products or erase their cart settings.','Open the shop again when you are ready for orders.']),
      _SellerLesson(icon: Icons.gavel_outlined, color: Colors.redAccent, titleKm: '៧. សុវត្ថិភាព និងវិវាទ', titleEn: '7. Safety and disputes', stepsKm: const ['បង្ហោះតែទំនិញពិត និងព័ត៌មានត្រឹមត្រូវ។','កុំលក់ទំនិញខុសច្បាប់ ក្លែងក្លាយ ឬបង្កគ្រោះថ្នាក់។','រក្សាភស្តុតាង Order ការទូទាត់ និងការដឹកជញ្ជូន។','ឆ្លើយតបបណ្ដឹងដោយសុភាព និងទាក់ទង Sesan Support ពេលត្រូវការ។'], stepsEn: const ['Post only real products with accurate information.','Do not sell illegal, counterfeit, or dangerous goods.','Keep order, payment, and delivery evidence.','Handle complaints politely and contact Sesan Support when needed.']),
    ];
    return Scaffold(backgroundColor: const Color(0xFFF5F7F5), appBar: AppBar(title: Text(appText(context, km: 'មគ្គុទេសក៍អ្នកលក់', en: 'Seller guide'), style: const TextStyle(fontFamily: 'Siemreap', fontSize: 17, fontWeight: FontWeight.bold)), backgroundColor: Colors.green.shade700, foregroundColor: Colors.white, centerTitle: true), body: ListView(padding: const EdgeInsets.fromLTRB(14,16,14,30), children: [Container(padding: const EdgeInsets.all(16), decoration: BoxDecoration(gradient: LinearGradient(colors:[Colors.green.shade700,Colors.green.shade500]),borderRadius: BorderRadius.circular(16)),child: Column(children:[const Icon(Icons.menu_book_rounded,color:Colors.white,size:38),const SizedBox(height:8),Text(appText(context,km:'រៀនលក់លើ Sesan App មួយជំហានម្ដងៗ',en:'Learn to sell on Sesan App step by step'),textAlign:TextAlign.center,style:const TextStyle(color:Colors.white,fontFamily:'Siemreap',fontWeight:FontWeight.bold,fontSize:16)),const SizedBox(height:4),Text(appText(context,km:'ចុចលើមេរៀនណាមួយដើម្បីបើកអាន',en:'Tap any lesson to read it'),style:const TextStyle(color:Colors.white70,fontFamily:'Siemreap',fontSize:11))])),const SizedBox(height:12),...lessons.map((lesson)=>_LessonCard(lesson:lesson))]));
  }
}
class _LessonCard extends StatelessWidget { final _SellerLesson lesson; const _LessonCard({required this.lesson}); @override Widget build(BuildContext context){final isEnglish=Localizations.localeOf(context).languageCode=='en';final steps=isEnglish?lesson.stepsEn:lesson.stepsKm;return Card(margin:const EdgeInsets.only(bottom:10),elevation:0,color:Colors.white,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(14),side:BorderSide(color:lesson.color.withOpacity(0.18))),child:ExpansionTile(leading:Container(width:42,height:42,decoration:BoxDecoration(color:lesson.color.withOpacity(0.10),borderRadius:BorderRadius.circular(11)),child:Icon(lesson.icon,color:lesson.color)),title:Text(isEnglish?lesson.titleEn:lesson.titleKm,style:const TextStyle(fontFamily:'Siemreap',fontWeight:FontWeight.bold,fontSize:14)),childrenPadding:const EdgeInsets.fromLTRB(16,0,16,14),children:[...steps.asMap().entries.map((entry)=>Padding(padding:const EdgeInsets.only(top:9),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(width:22,height:22,alignment:Alignment.center,decoration:BoxDecoration(color:lesson.color.withOpacity(0.10),shape:BoxShape.circle),child:Text('${entry.key+1}',style:TextStyle(color:lesson.color,fontSize:10,fontWeight:FontWeight.bold))),const SizedBox(width:9),Expanded(child:Text(entry.value,style:const TextStyle(fontFamily:'Siemreap',fontSize:12,height:1.55)))])))]));}}
class _SellerLesson { final IconData icon; final Color color; final String titleKm; final String titleEn; final List<String> stepsKm; final List<String> stepsEn; const _SellerLesson({required this.icon,required this.color,required this.titleKm,required this.titleEn,required this.stepsKm,required this.stepsEn}); }
