from pathlib import Path


def rep(s,a,b,label):
    if a not in s:
        raise SystemExit('MISSING '+label)
    print('OK',label)
    return s.replace(a,b,1)

p=Path('lib/chat_screen_legacy.dart')
s=p.read_text(encoding='utf-8')
s=rep(s,"title: const Text('ឆាត'),","title: Text(appText(context, km: 'ឆាត', en: 'Chat')),",'error appbar')
s=rep(s,"child: const Text('ត្រឡប់ក្រោយ'),","child: Text(appText(context, km: 'ត្រឡប់ក្រោយ', en: 'Back')),",'back')
s=rep(s,"userData?['name'] ?? 'អ្នកលក់',","userData?['name'] ?? appText(context, km: 'អ្នកលក់', en: 'Seller'),",'seller')
s=rep(s,"? '🟢 កំពុង Online'\n                            : _formatLastSeen(userData?['lastSeen']),","? '🟢 ${appText(context, km: 'កំពុង Online', en: 'Online')}'\n                            : _formatLastSeen(userData?['lastSeen']),",'online')
s=rep(s,"tooltip: 'មើលហាង',","tooltip: appText(context, km: 'មើលហាង', en: 'View shop'),",'view shop')
s=rep(s,"' Swipe ឆ្វេង លប់'","appText(context, km: ' អូសទៅឆ្វេងដើម្បីលុប', en: ' Swipe left to cancel')",'swipe')
s=rep(s,"isVireak ? \"ទីតាំងផ្ញើតាមវិរៈ\" : \"ទីតាំងទទួលឥវ៉ាន់\"","isVireak\n                    ? appText(context, km: 'ទីតាំងផ្ញើតាមវិរៈ', en: 'Vireak delivery location')\n                    : appText(context, km: 'ទីតាំងទទួលឥវ៉ាន់', en: 'Delivery location')",'location title')
s=rep(s,'"ខេត្ត/ក្រុង",','appText(context, km: "ខេត្ត/ក្រុង", en: "Province/City"),','province')
s=rep(s,'"ស្រុក/ខណ្ឌ",','appText(context, km: "ស្រុក/ខណ្ឌ", en: "District"),','district')
s=rep(s,'"សាខាវិរៈ",','appText(context, km: "សាខាវិរៈ", en: "Vireak branch"),','branch')
s=rep(s,'"អាសយដ្ឋាន",','appText(context, km: "អាសយដ្ឋាន", en: "Address"),','address')
s=rep(s,'child: Text("កំពុងផ្ញើ...", style: TextStyle(fontSize: 10)),','child: Text(appText(context, km: "កំពុងផ្ញើ...", en: "Sending..."), style: const TextStyle(fontSize: 10)),','sending')
s=rep(s,'return _buildAudioError("សម្លេងមិនមាន");','return _buildAudioError(appText(context, km: "សម្លេងមិនមាន", en: "Audio unavailable"));','audio unavailable')
s=rep(s,"  String _formatLastSeen(dynamic timestamp) {\n    if (timestamp == null) return 'អសកម្ម';\n    final time = (timestamp as Timestamp).toDate();\n    final diff = DateTime.now().difference(time);\n\n\n    if (diff.inMinutes < 1) return 'ទើបតែសកម្ម';\n    if (diff.inMinutes < 60) return 'សកម្ម ${diff.inMinutes} នាទីមុន';\n    if (diff.inHours < 24) return 'សកម្ម ${diff.inHours} ម៉ោងមុន';\n    return 'សកម្ម ${diff.inDays} ថ្ងៃមុន';\n  }","  String _formatLastSeen(dynamic timestamp) {\n    if (timestamp == null) return appText(context, km: 'អសកម្ម', en: 'Offline');\n    try {\n      final time = (timestamp as Timestamp).toDate();\n      final diff = DateTime.now().difference(time);\n      if (diff.inMinutes < 1) return appText(context, km: 'ទើបតែសកម្ម', en: 'Active just now');\n      if (diff.inMinutes < 60) {\n        return appText(context, km: 'សកម្ម ${diff.inMinutes} នាទីមុន', en: 'Active ${diff.inMinutes} min ago');\n      }\n      if (diff.inHours < 24) {\n        return appText(context, km: 'សកម្ម ${diff.inHours} ម៉ោងមុន', en: 'Active ${diff.inHours} hr ago');\n      }\n      if (diff.inDays < 7) {\n        return appText(context, km: 'សកម្ម ${diff.inDays} ថ្ងៃមុន', en: 'Active ${diff.inDays} days ago');\n      }\n      return DateFormat('dd/MM/yyyy').format(time);\n    } catch (_) {\n      return appText(context, km: 'មិនស្គាល់', en: 'Unknown');\n    }\n  }",'last seen')
p.write_text(s,encoding='utf-8')

p=Path('lib/create_invoice_sheet.dart')
s=p.read_text(encoding='utf-8')
s=rep(s,"import 'package:flutter/services.dart';\n","import 'package:flutter/services.dart';\nimport 'localized_text.dart';\n",'invoice import')
s=rep(s,'toolbarTitle: \'តម្រឹម QR Code\',','toolbarTitle: appText(context, km: \'តម្រឹម QR Code\', en: \'Crop QR Code\'),','android crop')
s=rep(s,"title: 'តឹម QR Code',","title: appText(context, km: 'តម្រឹម QR Code', en: 'Crop QR Code'),",'ios crop')
s=rep(s,'const Text(\n                        "បញ្ជីទំនិញ / Items List",','Text(\n                        appText(context, km: "បញ្ជីទំនិញ", en: "Items List"),','items')
s=rep(s,'label: const Text(\n                          "បន្ថែមទំនិញថ្មី",','label: Text(\n                          appText(context, km: "បន្ថែមទំនិញថ្មី", en: "Add another item"),','add item')
s=rep(s,'const Text(\n                        "ព័ត៌មានអ្នកទិញ / Buyer Info",','Text(\n                        appText(context, km: "ព័ត៌មានអ្នកទិញ", en: "Buyer Info"),','buyer info')
s=rep(s,'"ឈ្មោះអ្នកទិញ / Buyer Name",','appText(context, km: "ឈ្មោះអ្នកទិញ", en: "Buyer Name"),','buyer name')
s=rep(s,'"លេខទូរស័ព្ទ / Phone",','appText(context, km: "លេខទូរស័ព្ទ", en: "Phone"),','phone')
s=rep(s,'"អាសយដ្ឋាន / Address",','appText(context, km: "អាសយដ្ឋាន", en: "Address"),','buyer address')
s=rep(s,'"ថ្លៃដឹកជញ្ជូន / Shipping (៛)",','appText(context, km: "ថ្លៃដឹកជញ្ជូន (៛)", en: "Shipping (៛)"),','shipping')
s=rep(s,'const Text(\n          "QR Code សម្រាប់បង់ប្រាក់ (ABA / KHQR)",','Text(\n          appText(context, km: "QR Code សម្រាប់បង់ប្រាក់ (ABA / KHQR)", en: "Payment QR Code (ABA / KHQR)"),','qr')
s=rep(s,'          const Text(\n            "បង្កើតវិក្កយបត្រអាជីព",\n            style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),\n          ),','          Expanded(\n            child: Text(\n              appText(context, km: "បង្កើតវិក្កយបត្រអាជីព", en: "Create professional invoice"),\n              maxLines: 1,\n              overflow: TextOverflow.ellipsis,\n              style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold),\n            ),\n          ),','header')
s=rep(s,'"ទំនិញទី ${index + 1}",','appText(context, km: "ទំនិញទី ${index + 1}", en: "Item ${index + 1}"),','item number')
s=rep(s,'_buildInput("ឈ្មោះទំនិញ", CreateInvoiceSheet.items[index][\'desc\']!),','_buildInput(appText(context, km: "ឈ្មោះទំនិញ", en: "Product name"), CreateInvoiceSheet.items[index][\'desc\']!),','product name')
s=rep(s,'"ចំនួន",','appText(context, km: "ចំនួន", en: "Quantity"),','qty')
s=rep(s,'"តម្លៃរាយ ៛",','appText(context, km: "តម្លៃរាយ ៛", en: "Unit price ៛"),','unit price')
s=rep(s,'const Text(\n                "សរុបចុងក្រោយ៖",','Text(\n                appText(context, km: "សរុបចុងក្រោយ៖", en: "Grand total:"),','grand total')
s=rep(s,'_actionBtn(Icons.save, "Save", Colors.blue, () {','_actionBtn(Icons.save, appText(context, km: "រក្សាទុក", en: "Save"), Colors.blue, () {','save')
s=rep(s,'_actionBtn(Icons.camera_alt, "Capture", Colors.purple, () {','_actionBtn(Icons.camera_alt, appText(context, km: "ថតទុក", en: "Capture"), Colors.purple, () {','capture')
p.write_text(s,encoding='utf-8')
