platform :ios, '14.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(
    File.join('Flutter', 'Generated.xcconfig'),
    __dir__
  )

  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. Run flutter pub get first."
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end

  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}"
end

require File.expand_path(
  File.join(
    'packages',
    'flutter_tools',
    'bin',
    'podhelper'
  ),
  flutter_root
)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static

  # Keep SDWebImage compatible with Xcode 14.2
  pod 'SDWebImage', '5.19.7'
  pod 'SDWebImageWebPCoder', '0.14.0'

  flutter_install_all_ios_pods(
    File.dirname(File.realpath(__FILE__))
  )
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings[
        'IPHONEOS_DEPLOYMENT_TARGET'
      ] = '14.0'

      config.build_settings[
        'ENABLE_USER_SCRIPT_SANDBOXING'
      ] = 'NO'

      config.build_settings[
        'CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'
      ] = 'NO'

      config.build_settings[
        'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'
      ] = 'YES'

      config.build_settings[
        'SWIFT_VERSION'
      ] = '5.0'
    end

    # Fix BoringSSL-GRPC unsupported option '-G' on Xcode 16
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |build_file|
        next unless build_file.settings
        next unless build_file.settings['COMPILER_FLAGS']

        flags = build_file.settings['COMPILER_FLAGS']

        next unless flags.is_a?(String)

        flags = flags.gsub(
          '-GCC_WARN_INHIBIT_ALL_WARNINGS',
          ''
        )

        build_file.settings['COMPILER_FLAGS'] = flags.strip
      end
    end
  end
end